### ISSUE TITLE
Link for downloading DSRSID dataset

### ISSUE THREAD

**Issue by DhyanilMehta** [ushasi/CMIR-NET-A-deep-learning-based-model-for-cross-modal-retrieval-in-remote-sensing#1]
Hi, can you provide a link to download the raw DSRSID dataset? I will be needing it for my work. Thank you.

**Comment by ushasi** [comment]
Dear Dhyanil,
Plz find the following link to the DSRSID dataset.

https://drive.google.com/file/d/1DNuYSWH8y0sbGlnjXHtZGOpPhvzQHzPk/view?usp=sharing

Thanks!

**Comment by DhyanilMehta** [comment]
Thank you for sharing!
